# Configuração do MVP ArenaLake - Infraestrutura Core
services:

  # 1. GATEWAY / ROTEADOR
  traefik:
    image: traefik:v2.11
    environment:
      - DOCKER_API_VERSION=1.41
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8088:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - arenalake-net

  # 2. CÉREBRO DO PROCESSAMENTO (Spark Master)
  spark-master:
    image: bitnamilegacy/spark:3.5
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - arenalake-net

  # 3. DATA LAKE (MinIO)
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      # Senhas dinâmicas puxadas do arquivo .env
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000" # Porta da API
      - "9001:9001" # Porta do Painel Web
    volumes:
      - minio_data:/data
    networks:
      - arenalake-net

  # 4. IMAGEM BASE DO WORKSPACE (Garante o Plug-and-Play automático)
  workspace-builder:
    build:
      context: .
      dockerfile: docker/Dockerfile.workspace
    image: arenalake-workspace:latest
    command: echo "Imagem arenalake-workspace construída com sucesso!"

  # 4. CÉREBRO DA OPERAÇÃO (Backend FastAPI)
  portal:
    build: 
      context: ./portal-compute
      dockerfile: Dockerfile
    env_file:
       - .env
    environment:
      - HOST_PROJECT_PATH=${PWD}
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - arenalake-net

networks:
  arenalake-net:
    driver: bridge

# VOLUME PERSISTENTE
volumes:
  minio_data: