# Usa a imagem oficial do VS Code no navegador
FROM codercom/code-server:latest

# Entra como root para poder instalar pacotes no sistema
USER root

# Atualiza o Linux, instala o Python3 e o PIP
RUN apt-get update && \
    apt-get install -y python3 python3-pip default-jre && \
    rm -rf /var/lib/apt/lists/*

# Instala as bibliotecas de dados globalmente no container
RUN pip3 install --no-cache-dir pandas boto3 s3fs pyspark==3.5.6 dotenv ipykernel --break-system-packages

# Volta para o usuário padrão por segurança
USER coder
