singleuser:
  image:
    name: l1k3d/arenalake-jupyter-spark
    tag: "1.0"

  cmd: null
  defaultUrl: "/lab"

  extraEnv:
    AWS_ACCESS_KEY_ID:
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: AWS_ACCESS_KEY_ID

    AWS_SECRET_ACCESS_KEY:
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: AWS_SECRET_ACCESS_KEY

  serviceAccountName: default

  extraPodConfig:
    automountServiceAccountToken: true

hub:
  config:
    KubeSpawner:
      delete_failed_pods: False

rbac:
  create: true
